# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXINTL    = sphinx-intl
SOURCEDIR     = source
BUILDDIR      = build
LANGOPTS      = "-l ko"


# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

# Update template file from base file. use when original document sources were chaned.
krupdate: Makefile
	make gettext
	@$(SPHINXINTL) update -p $(BUILDDIR)/gettext -l ko

# build html with korean translation. use it for checking translation works. 
krhtml: Makefile
	make -e SPHINXOPTS="-D language='ko'" html

protoc:
	docker run --rm \
  		-v $(shell pwd)/source/api:/out \
		  -v $(shell pwd)/source/_templates/protoc-markdown.tmpl:/template.tmpl \
  		-v $(shell go env GOPATH)/src/github.com/aergoio/aergo/aergo-protobuf/proto:/protos \
  		pseudomuto/protoc-gen-doc --doc_opt=/template.tmpl,rpc-autogenerated.md rpc.proto blockchain.proto metric.proto
