# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

protoc:
	docker run --rm \
  		-v $(shell pwd)/source/api:/out \
		  -v $(shell pwd)/source/_templates/protoc-markdown.tmpl:/template.tmpl \
  		-v $(shell go env GOPATH)/src/github.com/aergoio/aergo/aergo-protobuf/proto:/protos \
  		pseudomuto/protoc-gen-doc --doc_opt=/template.tmpl,rpc-autogenerated.md rpc.proto blockchain.proto metric.proto